gcc -o 01._The_maximum_and_minimum_of_three_numbers.exe   01._The_maximum_and_minimum_of_three_numbers.c
gcc -o 02._The_sum_of_numbers.exe                         02._The_sum_of_numbers.c
gcc -o 03._The_product_of_numbers.exe                     03._The_product_of_numbers.c
gcc -o 04._The_factorial_of_a_number_n.exe                04._The_factorial_of_a_number_n.c
gcc -o 05._Mean_and_standard_deviation.exe                05._Mean_and_standard_deviation.c
gcc -o 06._Three-digit_Armstrong_numbers.exe              06._Three-digit_Armstrong_numbers.c
gcc -o 07._Four-digit_Armstrong_numbers.exe               07._Four-digit_Armstrong_numbers.c
gcc -o 08._Greatest_Common_Divisor.exe                    08._Greatest_Common_Divisor.c
gcc -o 09._Prime_number.exe                               09._Prime_number.c
gcc -o 10._N_prime_numbers.exe                            10._N_prime_numbers.c
gcc -o 11._Divisors_of_a_number.exe                       11._Divisors_of_a_number.c
gcc -o 12._Divisibility_by_3.exe                          12._Divisibility_by_3.c
gcc -o 13._Quadratic_equation.exe                         13._Quadratic_equation.c
gcc -o 14._Capitalization.exe                             14._Capitalization.c
gcc -o 15._Annuity.exe                                    15._Annuity.c
gcc -o 16._Minimum_element_of_a_sequence.exe              16._Minimum_element_of_a_sequence.c
gcc -o 17._Sum_of_two_matrices.exe                        17._Sum_of_two_matrices.c
gcc -o 18._Product_of_a_matrix_and_a_number.exe           18._Product_of_a_matrix_and_a_number.c
gcc -o 19._Product_of_two_matrices.exe                    19._Product_of_two_matrices.c
gcc -o 20._Sorting.exe                                    20._Sorting.c
gcc -o 21._Bubble_sort_algorithm.exe                      21._Bubble_sort_algorithm.c